# Generated by Django 5.2.7 on 2026-01-09 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Коробка',
                'verbose_name_plural': 'Коробки',
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Клей',
                'verbose_name_plural': 'Клеи',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Браки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.order')),
            ],
            options={
                'verbose_name': 'Рулон',
                'verbose_name_plural': 'Рулоны',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Время начало')),
                ('time_end', models.TimeField(verbose_name='Время конца')),
                ('plan', models.IntegerField(null=True, verbose_name='План')),
                ('done', models.IntegerField(null=True, verbose_name='Выполнено')),
                ('count_box', models.IntegerField(null=True, verbose_name='Количество коробок')),
                ('count_clue', models.IntegerField(null=True, verbose_name='Количество клея кг.')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.box')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.clue')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.machine')),
                ('marriage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.marriage')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.order')),
                ('rolls', models.ManyToManyField(to='production.roll')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.work')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Рабочие смены',
            },
        ),
    ]
