# Generated by Django 4.2.27 on 2026-01-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight_one_piece',
            field=models.IntegerField(null=True, verbose_name='вес одной шт. в граммах'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='time_delta',
            field=models.IntegerField(default=0, verbose_name='Время смены'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roll',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.box', verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='clue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.clue', verbose_name='Клей'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.machine', verbose_name='агрегат'),
        ),
        migrations.RemoveField(
            model_name='workingshift',
            name='marriage',
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='plan',
            field=models.IntegerField(default=48000, null=True, verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='rolls',
            field=models.ManyToManyField(to='production.roll', verbose_name='Рулоны'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='time_end',
            field=models.TimeField(verbose_name='Время конца смены'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='time_start',
            field=models.TimeField(verbose_name='Время начало смены'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.RemoveField(
            model_name='workingshift',
            name='work',
        ),
        migrations.CreateModel(
            name='MarriageCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_pieces', models.IntegerField(verbose_name='Количество в шт')),
                ('count_weight', models.IntegerField(verbose_name='Количество в гр.')),
                ('marriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.marriage', verbose_name='брак')),
                ('working_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workingshift', verbose_name='рабочая смена')),
            ],
            options={
                'verbose_name': 'Вид брака',
                'verbose_name_plural': 'Виды брака',
            },
        ),
        migrations.AddField(
            model_name='workingshift',
            name='marriage',
            field=models.ManyToManyField(through='production.MarriageCount', to='production.marriage', verbose_name='Вид брака'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='work',
            field=models.ManyToManyField(to='production.work', verbose_name='Работы'),
        ),
    ]
