# Generated by Django 4.2.27 on 2026-01-25 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_order_weight_one_piece_workingshift_time_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_size',
            field=models.CharField(default='0x0x0', help_text='250x130x85', max_length=11, verbose_name='Размер пакета'),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(help_text='390x290x200', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.box', verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='clue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.clue', verbose_name='Клей'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='count_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество коробок'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='count_clue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество клея кг.'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='done',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.machine', verbose_name='агрегат'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='plan',
            field=models.IntegerField(blank=True, default=48000, null=True, verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='time_delta',
            field=models.IntegerField(default=8, verbose_name='Время смены'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='time_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Время конца смены'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='time_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Время начало смены'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
