# Generated by Django 4.2.27 on 2026-01-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_order_package_size_alter_box_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='gramage',
            field=models.IntegerField(blank=True, default=None, help_text='65 гр/м', null=True, verbose_name='Граммаж бумаги'),
        ),
        migrations.AddField(
            model_name='roll',
            name='length',
            field=models.IntegerField(blank=True, default=None, help_text='Длина рулона в метрах', null=True, verbose_name='Длина рулона'),
        ),
        migrations.AddField(
            model_name='roll',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, help_text='Производитель рулона', max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='roll',
            name='roll_name',
            field=models.CharField(blank=True, default=None, help_text='Мешочная или упаковочная', max_length=255, null=True, verbose_name='Вид бумаги'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.box', verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='clue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.clue', verbose_name='Клей'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='rolls',
            field=models.ManyToManyField(blank=True, null=True, to='production.roll', verbose_name='Рулоны'),
        ),
    ]
