# Generated by Django 4.2.27 on 2026-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_roll_gramage_roll_length_roll_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='paper_size',
            field=models.IntegerField(blank=True, default=0, help_text='Формат бумаги', null=True, verbose_name='Размер бумаги'),
        ),
    ]
