# Generated by Django 4.2.27 on 2026-02-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_roll_paper_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingshift',
            options={'ordering': ['-date'], 'verbose_name': 'Рабочая смена', 'verbose_name_plural': 'Рабочие смены'},
        ),
        migrations.AlterField(
            model_name='order',
            name='weight_one_piece',
            field=models.FloatField(null=True, verbose_name='вес одной шт. в граммах'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='time_delta',
            field=models.FloatField(default=8, editable=False, verbose_name='Время смены (часы)'),
        ),
        migrations.CreateModel(
            name='ImageShiftAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shift_acts', verbose_name='Фото акта')),
                ('working_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workingshift', verbose_name='рабочая смена')),
            ],
        ),
    ]
