# Generated by Django 4.2.27 on 2026-02-24 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_workingshift_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageshiftact',
            options={'ordering': ('-uploaded_at',), 'verbose_name': 'Фото акта', 'verbose_name_plural': 'Фото актов'},
        ),
        migrations.AddField(
            model_name='imageshiftact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imageshiftact',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 1, 0, 0), verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageshiftact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shift_acts/%Y/%m/%d/', verbose_name='Фото акта'),
        ),
    ]
